# Generated by Django 4.0.3 on 2022-07-26 16:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.CharField(editable=False, max_length=12, primary_key=True, serialize=False, unique=True)),
                ('profile_pic', models.ImageField(default='default.jpg', upload_to='UserDps/')),
                ('gender', models.CharField(max_length=10)),
                ('location', models.CharField(max_length=50)),
                ('dob', models.DateField(null=True)),
                ('age', models.PositiveIntegerField(default=0)),
                ('phone_no', models.CharField(max_length=15)),
                ('marital_status', models.CharField(max_length=15)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('reg_user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'User Profiles',
                'ordering': ['reg_user'],
            },
        ),
        migrations.CreateModel(
            name='YourStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.TextField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('victim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Experiences',
                'ordering': ['victim', 'created'],
            },
        ),
        migrations.CreateModel(
            name='UserAppointment',
            fields=[
                ('id', models.CharField(editable=False, max_length=8, primary_key=True, serialize=False)),
                ('medic', models.CharField(max_length=150)),
                ('appointment_date', models.DateField()),
                ('appointment_time', models.TimeField()),
                ('type_session', models.CharField(max_length=20)),
                ('duration', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=10)),
                ('scheduled', models.DateTimeField(auto_now_add=True)),
                ('edited', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='users.userprofile')),
            ],
            options={
                'verbose_name_plural': 'Appointments',
                'ordering': ['scheduled'],
            },
        ),
        migrations.CreateModel(
            name='AskQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('asked', models.DateTimeField(auto_now_add=True)),
                ('questioner', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='users.userprofile')),
            ],
            options={
                'verbose_name_plural': 'FAQs',
                'ordering': ['asked'],
            },
        ),
    ]
