# Generated by Django 4.0.3 on 2022-07-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userappointment',
            name='approval',
            field=models.CharField(default='', max_length=20),
        ),
    ]
