# Generated by Django 4.0.3 on 2022-07-28 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userappointment_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userappointment',
            name='approval',
            field=models.CharField(max_length=20),
        ),
    ]
