# Generated by Django 4.0.3 on 2022-07-28 09:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_userappointment_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userappointment',
            name='company',
        ),
    ]
