# Generated by Django 4.0.3 on 2022-07-28 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_alter_feedback_options_feedback_counsellor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='counsellor',
            field=models.CharField(max_length=150),
        ),
    ]
