# Generated by Django 4.0.3 on 2022-07-28 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_feedback_counsellor'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userappointment',
            options={'ordering': ['-scheduled'], 'verbose_name_plural': 'Appointments'},
        ),
    ]
