# Generated by Django 4.0.3 on 2022-07-28 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellors', '0002_alter_workprofile_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workprofile',
            name='closing_hours',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='workprofile',
            name='opening_hours',
            field=models.TimeField(null=True),
        ),
    ]
