# Generated by Django 4.0.3 on 2022-07-28 06:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('counsellors', '0003_alter_workprofile_closing_hours_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workprofile',
            name='name',
            field=models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
